### ISSUE TITLE
Refactor of the Manager Interface

### ISSUE THREAD

**Issue by tcaiazzi** [KatharaFramework/Kathara#154]
Refactor of the Manager Interface to expose more comfortable APIs. 

The refactor will include: 

- [x] Decouple CLI logic from Business Logic (#155).
- [x] Add class `DockerMachineInfo` to handle Docker stats about running machines.
- [x] Add class `DockerLinkInfo` to handle Docker stats about deployed networks.
- [x] Add class `KubernetesMachineInfo` to handle Kubernetes stats about running machines.
- [x] Add class `KubernetesLinkInfo` to handle Kubernetes stats about deployed networks.
- [x] Add `get_machines_stats` method to replace `get_lab_info`.
- [x] Add `get_machine_stats` method.
- [x] Add `get_links_stats` method (Docker).
- [x] Add `get_link_stats` method (Docker).
- [x] Add `get_links_stats` method (Kubernetes).
- [x] Add `get_link_stats` method (Kubernetes).
- [x] Refactor of the `get_machine_api_object` method (following the signature suggested by @Skazza94 below).
- [x] Add `get_machines_api_objects` method 
- [x] Add `get_link_api_object` method.
- [x] Add `get_links_api_object` method.
- [x] Move `get_formatted_info` into `cli.ui` package.
- [x] Add the support for both `lab_hash` and `lab_name` parameters in `undeploy_lab` method (temporary workaround #152).
- [x] Add the support for both `lab_hash` and `lab_name` parameters in `connect_tty` method (temporary workaround #152).
- [x] Add the support for both `lab_hash` and `lab_name` parameters in `exec` method (temporary workaround #152).

**N.B.** The signature of the methods are provided by @Skazza94 in the comment below.

**Comment by Skazza94** [comment]
I suggest to follow this plan.
1. Methods for retrieving machines and links info:
```python3
get_machines_info(lab_hash: str = None, lab_name: str = None, all_users: bool = False, stream: bool = False) -> Union[Generator[List[MachineInfo], None, None], List[MachineInfo]]
get_machine_info(machine_name: str, lab_hash: str = None, lab_name: str = None, all_users: bool = False, stream: bool = False) -> Union[Generator[MachineInfo, None, None], MachineInfo]
get_links_info(lab_hash: str = None, lab_name: str = None, all_users: bool = False, stream: bool = False) -> Union[Generator[List[LinkInfo], None, None], List[LinkInfo]]
get_link_info(link_name: str, lab_hash: str = None, lab_name: str = None, all_users: bool = False, stream: bool = False) -> Union[Generator[LinkInfo, None, None], LinkInfo]
```
Where `MachineInfo` and `LinksInfo` are two new classes that handle the statistics logic and formatting.

2. Method for retrieving specific API objects:
```python3
get_machines_api_objects(lab_hash: str = None, lab_name: str = None) -> List[Any]
get_machine_api_object(machine_name: str, lab_hash: str = None, lab_name: str = None) -> Any
get_links_api_objects(lab_hash: str = None, lab_name: str = None) -> List[Any]
get_link_api_object(link_name: str, lab_hash: str = None, lab_name: str = None) -> Any
```

3. Refactor existing methods to support both `lab_hash` and `lab_name` parameters. If none of them is specified, the method returns an Exception. If `lab_name` is specified, it internally computes the `lab_hash`:
```python3
undeploy_lab(lab_hash: str = None, lab_name: str = None, selected_machines: Set[str] = None) -> None
connect_tty(machine_name: str, lab_hash: str = None, lab_name: str = None, shell: str = None, logs: bool = False) -> None
exec(machine_name: str, lab_hash: str = None, lab_name: str = None, command: str) -> Generator[Tuple[bytes, bytes], None, None]
```
