### ISSUE TITLE
Move `Machine.startup_commands` into `Machine.meta`and make `Machine.capabilities` a constant

### ISSUE THREAD

**Issue by Skazza94** [KatharaFramework/Kathara#206]
There is no reason why `Machine.startup_commands` should be a separate attribute with respect to `Machine.meta`.
Moreover,  `Machine.capabilities` is never changed (is a read-only attribute), we can convert it to a constant located in `Machine.py`.

This changes will:
- [x] Put `Machine.startup_commands` into `Machine.meta`
- [x] Create a `get_startup_commands` getter
- [x] Refactor dependent code
- [x] Move the `Machine.capabilities` into a constant `MACHINE_CAPABILITIES` and refactor code accordingly
